name: GraalVM Native Image builds
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  build:
    name: HelloWorld on ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and run timetable-solver
        run: |
              ./mvnw package -Pnative
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: timetable-solver-function
          path: target/function.zip
